SELECT OUTS.ANIMAL_ID, OUTS.ANIMAL_TYPE, OUTS.NAME FROM
ANIMAL_OUTS AS OUTS LEFT JOIN ANIMAL_INS AS INS
ON OUTS.ANIMAL_ID = INS.ANIMAL_ID
WHERE NOT OUTS.SEX_UPON_OUTCOME = INS.SEX_UPON_INTAKE

https://programmers.co.kr/learn/courses/30/lessons/59045
